version: '3'
services:
  movies:
    image: vishnu155/bus155:latest
    ports:
      -  "94:80"
    deploy:
      replicas: 3
  train:
    image: vamc2001/phonepaytrain:v1
    ports:
      -  "95:80"
    deploy:
      replicas: 3
  dth:
    image: vamc2001/phonepaydth:v1
    ports:
      -  "96:80"
    deploy:
      replicas: 3
